### ISSUE TITLE
SwiperFlatList autoplay is not working properly in Android.

### ISSUE THREAD

**Issue by SukumarSmart** [gusgard/react-native-swiper-flatlist#17]
Here is my code 
`<SwiperFlatList
           autoplayDelay={2.5}
           index={1}
           autoplay
           autoplayLoop
           removeClippedSubviews
           >
</SwiperFlatList>`
thanks in advance.

**Comment by zrone** [comment]
Hello, I found the same iusse in Android and I modify the source code to support android. may be can help you. Insert code to number 116.
`if(Platform.OS === "android") {
      this._autoplay(index)
    }`
reason of the question: It's not auto run Android  for func `onMomentumScrollEnd` when exec `scrollToIndex`, you must be dispatch it yourself.

**Comment by SukumarSmart** [comment]
Thanks @zrone for reply.

**Comment by gusgard** [comment]
@SukumarSmart Sorry for the delay, I will take a look to this issue this weekend.

**Comment by gusgard** [comment]
Fixed and released in [1.0.8](https://github.com/gusgard/react-native-swiper-flatlist/releases/tag/1.0.8)

Thanks to both of you for found and fix the issue

**Comment by jigaroza287** [comment]
Hi,
I am still facing the autoplay issue, it seems it's scrolling very fast on Android. Here is my code:
Note: "images" is an Array of URL strings

```
<View style={styles.sliderContainer}>
  <SwiperFlatList
    autoplay
    autoplayDelay={3}
    autoplayLoop
    showPagination
    data={images}
    renderItem={this._renderImageSliderItems}
  />
</View>

_renderImageSliderItems = ({ item }) => {
  return (
    <View>
      <ImageLoad
        style={this.state.sliderImage}
        isShowActivity={false}
        source={{ uri: item }}
      />
    </View>
  );
};

```

**Comment by IntelliJAbhishek** [comment]
@jigaroza287 auto play is very fast even if autoplaydelay set to 10. This problem occurs  when we have images uri.

Any fix for that?

**Comment by jigaroza287** [comment]
@IntelliJAbhishek no, I didn't find any solution. 
The problem does not occur for all the Android devices. I found it working on most of the Androids, a few, particularly I tested on a iBall Android Tablet with Android 6.0, Marshmallow, it has the same behaviour as you said, autoplay is too fast regardless of whatever delay you provide.

**Comment by IntelliJAbhishek** [comment]
@jigaroza287 I'm also getting same behaviour in marshmallow.

**Comment by IntelliJAbhishek** [comment]
Create a issue here https://github.com/gusgard/react-native-swiper-flatlist/issues/42

**Comment by gusgard** [comment]
In what version of Android is this reproducible? Can I reproduce it in an emulator or needs to be a real device? Did you try using `FastImage ` https://github.com/DylanVann/react-native-fast-image instead of `Image`

**Comment by IntelliJAbhishek** [comment]
@gusgard i think this is only happen when autoplay loop is set and we are using remote debugging.

**Comment by IntelliJAbhishek** [comment]
@gusgard  fixed im latest version

**Comment by gusgard** [comment]
Can someone else confirm that it is only happen when debugging is enabled? So I can close this issue.

**Comment by chahalrohit** [comment]
put this code or call inside componentDidMount or useEffect
 if ( imageArrayLength !== 0 && imageArrayLength !== 1 ) {
            scrollRef.current.scrollToIndex({
              index: 1,
              animated: true,
            });
          }

**Comment by Vishwa-33** [comment]
import { View, Text, FlatList,Image } from 'react-native'
import React from 'react';
import { useState } from 'react';
import { SwiperFlatList } from 'react-native-swiper-flatlist';

import { widthPercentageToDP as wp, heightPercentageToDP as hp } from 'react-native-responsive-screen';

const image1 =require('../component/constants/banner_image_min.jpg');
const image2 =require('../component/constants/banner.jpg');
const image3 =require('../component/constants/banner_image_min.jpg');

const image4 =require('../component/constants/banner_image_min.jpg');


const Sample = () => {

    

    const [data,setData] = useState([

        {
            items:[
                image1,
                image2,
                image3,
                image4,

            ]
        }

    ]


    )

    

  return (
    <View>
      <SwiperFlatList
      autoplay
      autoplayDelay={2}
      autoplayLoop
      showPagination
      index={2}
      data={data[0].items}
      pagingEnabled
      horizontal
    //   removeClippedSubviews
      

      renderItem={({item,index})=>{
        return <Image source={item} style={{width:wp(100),height:hp(22),marginTop:100}} />
      }

      }
      />
    </View>
  )
}

export default Sample


its working..⏰👀
